//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accenture.MyWizard.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IngrainResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IngrainResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accenture.MyWizard.Resource.IngrainResx", typeof(IngrainResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string AddFeatureSuccess {
            get {
                return ResourceManager.GetString("AddFeatureSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes should not be Null.
        /// </summary>
        public static string AttributesNull {
            get {
                return ResourceManager.GetString("AttributesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CorrelatioUID is Empty.
        /// </summary>
        public static string CorrelatioUIDEmpty {
            get {
                return ResourceManager.GetString("CorrelatioUIDEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data For CorrelationId.
        /// </summary>
        public static string CorrelatioUIdNotMatch {
            get {
                return ResourceManager.GetString("CorrelatioUIdNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved Successfully..
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Engineering completed success.
        /// </summary>
        public static string DataEngineering {
            get {
                return ResourceManager.GetString("DataEngineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Model completed successfully.
        /// </summary>
        public static string DeleteModelcompleted {
            get {
                return ResourceManager.GetString("DeleteModelcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy Model completed successfully.
        /// </summary>
        public static string DeployModelcompleted {
            get {
                return ResourceManager.GetString("DeployModelcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate user.
        /// </summary>
        public static string DuplicateUser {
            get {
                return ResourceManager.GetString("DuplicateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data Found in dataabase for CorrelationId.
        /// </summary>
        public static string EmptyData {
            get {
                return ResourceManager.GetString("EmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Request Body.
        /// </summary>
        public static string EmptyReqBody {
            get {
                return ResourceManager.GetString("EmptyReqBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at Data Engineering.
        /// </summary>
        public static string EngineeringDataError {
            get {
                return ResourceManager.GetString("EngineeringDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at Data Engineering:.
        /// </summary>
        public static string ErrorDataEngineering {
            get {
                return ResourceManager.GetString("ErrorDataEngineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at Data Transformation.
        /// </summary>
        public static string ErrorDataTransformation {
            get {
                return ResourceManager.GetString("ErrorDataTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at Model Engineering.
        /// </summary>
        public static string ErrorModelEngineering {
            get {
                return ResourceManager.GetString("ErrorModelEngineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fail.
        /// </summary>
        public static string FailedStatusCode {
            get {
                return ResourceManager.GetString("FailedStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data on File.
        /// </summary>
        public static string FileEmpty {
            get {
                return ResourceManager.GetString("FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application supports only .csv and .xlsx or xls.
        /// </summary>
        public static string FileExtensionNotSupport {
            get {
                return ResourceManager.GetString("FileExtensionNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Exist.
        /// </summary>
        public static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File Not Valid.
        /// </summary>
        public static string FileNotValid {
            get {
                return ResourceManager.GetString("FileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size is Exceeded..
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTId is Empty.
        /// </summary>
        public static string HTIDEmpty {
            get {
                return ResourceManager.GetString("HTIDEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputData Empty.
        /// </summary>
        public static string InputData {
            get {
                return ResourceManager.GetString("InputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Inputs are Empty.
        /// </summary>
        public static string InputEmpty {
            get {
                return ResourceManager.GetString("InputEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelName or ClientUID or DeliverConstructID is null.
        /// </summary>
        public static string InputFieldsAreNull {
            get {
                return ResourceManager.GetString("InputFieldsAreNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Inputs are Empty.
        /// </summary>
        public static string InputsEmpty {
            get {
                return ResourceManager.GetString("InputsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Processing...
        /// </summary>
        public static string InternalServererror {
            get {
                return ResourceManager.GetString("InternalServererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid browser name.
        /// </summary>
        public static string InValidBrowser {
            get {
                return ResourceManager.GetString("InValidBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name.
        /// </summary>
        public static string InValidFileName {
            get {
                return ResourceManager.GetString("InValidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientId/DCUID is InValid.
        /// </summary>
        public static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input data.
        /// </summary>
        public static string InvalidInputData {
            get {
                return ResourceManager.GetString("InvalidInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Valid logged in User.
        /// </summary>
        public static string InValidLoggedInUser {
            get {
                return ResourceManager.GetString("InValidLoggedInUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use proper token.
        /// </summary>
        public static string InValidToken {
            get {
                return ResourceManager.GetString("InValidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName/UserId is Invalid.
        /// </summary>
        public static string InValidUser {
            get {
                return ResourceManager.GetString("InValidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Mails are not sent...
        /// </summary>
        public static string MailNotSent {
            get {
                return ResourceManager.GetString("MailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping has been Done..
        /// </summary>
        public static string Mapping {
            get {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Engineering completed successfully.
        /// </summary>
        public static string ModelEngineeringcompleted {
            get {
                return ResourceManager.GetString("ModelEngineeringcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name already exist. Kindly proceed with different name..
        /// </summary>
        public static string ModelNameExist {
            get {
                return ResourceManager.GetString("ModelNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Models Failed while Training.
        /// </summary>
        public static string ModelsFailedTraining {
            get {
                return ResourceManager.GetString("ModelsFailedTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No models trained for this correlation id, to proceed Deploy Model.
        /// </summary>
        public static string Nomodelstrained {
            get {
                return ResourceManager.GetString("Nomodelstrained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found for Correlation Id in Deploy Model.
        /// </summary>
        public static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found for Insta Id/Correlation Id.
        /// </summary>
        public static string NorecordfoundforID {
            get {
                return ResourceManager.GetString("NorecordfoundforID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction completed successfully.
        /// </summary>
        public static string Predictioncompleted {
            get {
                return ResourceManager.GetString("Predictioncompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction Failed.
        /// </summary>
        public static string PredictionFailed {
            get {
                return ResourceManager.GetString("PredictionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refit Model completed successfully.
        /// </summary>
        public static string RefitModelcompleted {
            get {
                return ResourceManager.GetString("RefitModelcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PythonProcess Initiated.
        /// </summary>
        public static string RunPython {
            get {
                return ResourceManager.GetString("RunPython", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Character are not allowed.
        /// </summary>
        public static string SpecialCharacterNotAllowed {
            get {
                return ResourceManager.GetString("SpecialCharacterNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string SuccessStatusCode {
            get {
                return ResourceManager.GetString("SuccessStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload success.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID is Empty.
        /// </summary>
        public static string UserIdEmpty {
            get {
                return ResourceManager.GetString("UserIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID does not exist.
        /// </summary>
        public static string UserIdNotMatch {
            get {
                return ResourceManager.GetString("UserIdNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password incorrect..
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFId is Empty.
        /// </summary>
        public static string WFIDEmpty {
            get {
                return ResourceManager.GetString("WFIDEmpty", resourceCulture);
            }
        }
    }
}
