import { Injectable } from '@angular/core';
import { ApiService } from 'src/app/_services/api.service';
import { tap } from 'rxjs/operators';
import { CoreUtilsService } from 'src/app/_services/core-utils.service';
import { LocalStorageService } from 'src/app/_services/local-storage.service';


@Injectable({
  providedIn: 'root'
})
export class InferenceModelsService {
  autoSampleGeneratedIE = [];
  constructor(private api: ApiService, private coreUtilsService: CoreUtilsService, private ls: LocalStorageService) { }

  // DeleteIEModel?correlationId=26a82223-3372-4ab3-80a0-c1a286da9401 
  deleteIEModel(correlationId) {
    return this.api.get('DeleteIEModel', { 'correlationId': correlationId });
  }

  // api/GetModelInferences?correlationId=18e714ca-e137-4065-93b6-5fbd2329f655&applicationId&inferenceconfigId&autogenerated=true
  getModelInferences(correlationId) {
    const params = {
      'correlationId': correlationId,
      'applicationId': '',
      'inferenceconfigId': '',
      'autogenerated': true
    }

    return this.api.get('GetModelInferences', params);
  }

  getIEModel(clientId: string, dCId: string, userId: string) {
    const Environment = (this.coreUtilsService.isNil(sessionStorage.getItem('Environment')) == false) ? sessionStorage.getItem('Environment') : sessionStorage.getItem('env');
    const RequestType = sessionStorage.getItem('RequestType');
    if (Environment === 'PAM' || Environment === 'FDS') {
      return this.api.get('GetIEModel', { 'clientId': clientId, 'dCId': dCId, 'userId': userId, 'FunctionalArea': RequestType });
    } else {
      return this.api.get('GetIEModel', { 'clientId': clientId, 'dCId': dCId, 'userId': userId });
    }
  }

  deleteIEConfig(inferenceConfigId) {
    // DeleteIEConfig?inferenceConfigId=123
    return this.api.get('DeleteIEConfig', { 'inferenceConfigId': inferenceConfigId });
  }

  // /api/GenerateInference?correlationId=8257c968-56ef-4eb3-bec9-5925ef2c6d06&inferenceConfigId=535d1cc2-0c37-4038-8bad-1f684be0311c&userId=mywizardsystemdataadmin@mwphoenix.onmicrosoft.com
  // &isNewRequest=true
  // {
  //     "Status": "P", // N ,O ,P,E ,C
  //     "Message": "In-Progress",
  //     "Progress": "10",
  //     "CorrelationId": "f3b83a62-3b08-4ce2-bb8c-cb3c9625b819",
  //     "RequestId": "99305b6b-2868-49ae-9d45-3cead12e105b"
  // } 

  // On click of GenerateInference API pass isNewRequest=true boolean value
  // --------------- isNewRequest=false

  generateInferences(params) {
    return this.api.post('GenerateInference', null, params);
  }

  getApplications(env) {
    return this.api.get('GetApplications', { 'environment': env })
  }

  addApplication( params) {
    // ingrain/api/AddApplication
    params['BaseURL'] = this.api.ingrainAPIURL;
    return this.api.post('AddApplication', params)
  }

  publishInference(payload) {
    return this.api.post('PublishInference', payload);
  }

  getPublishedInferences(params) {
    // api/GetPublishedInferences?correlationId=eb54e08d-373b-4341-8408-c6cca080379d&applicationId=&inferenceconfigId=
    return this.api.get('GetPublishedInferences', params)
  }
  // api/GetApplications?
}

